openapi: 3.2.0
info:
  title: Dash Country Data API
  description: Open Source APIs for all!
  contact:
    name: Know more about API Dash
    url: https://apidash.dev/
  version: 0.0.4
tags:
- name: Country Data
paths:
  /country/codes:
    get:
      tags:
      - Country Data
      summary: Get Country Code Dictionary
      operationId: get_country_code_dictionary_country_codes_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /country/data:
    get:
      tags:
      - Country Data
      summary: Get Country Data
      operationId: get_country_data_country_data_get
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
          title: Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /country/flag:
    get:
      tags:
      - Country Data
      summary: Get Country Flag
      operationId: get_country_flag_country_flag_get
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
          title: Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /country/name:
    get:
      tags:
      - Country Data
      summary: Get Country Name
      operationId: get_country_name_country_name_get
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
          title: Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /country/officialname:
    get:
      tags:
      - Country Data
      summary: Get Official Country Name
      operationId: get_official_country_name_country_officialname_get
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
          title: Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /country/subdivisions:
    get:
      tags:
      - Country Data
      summary: Get Country Subdivisions
      operationId: get_country_subdivisions_country_subdivisions_get
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
          title: Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /login
